[package]
name = "post-queue-processor"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
license-file = "LICENSE"

[dependencies]
rocket = "=0.5.0-rc.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
